// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeerRequirement_PickStrategy int32

const (
	BeerRequirement_STRATEGY_RANDOM BeerRequirement_PickStrategy = 0
	BeerRequirement_STRATEGY_OLDEST BeerRequirement_PickStrategy = 1
)

// Enum value maps for BeerRequirement_PickStrategy.
var (
	BeerRequirement_PickStrategy_name = map[int32]string{
		0: "STRATEGY_RANDOM",
		1: "STRATEGY_OLDEST",
	}
	BeerRequirement_PickStrategy_value = map[string]int32{
		"STRATEGY_RANDOM": 0,
		"STRATEGY_OLDEST": 1,
	}
)

func (x BeerRequirement_PickStrategy) Enum() *BeerRequirement_PickStrategy {
	p := new(BeerRequirement_PickStrategy)
	*p = x
	return p
}

func (x BeerRequirement_PickStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeerRequirement_PickStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (BeerRequirement_PickStrategy) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x BeerRequirement_PickStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeerRequirement_PickStrategy.Descriptor instead.
func (BeerRequirement_PickStrategy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13, 0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	LatestCheckin int64                  `protobuf:"varint,4,opt,name=latest_checkin,json=latestCheckin,proto3" json:"latest_checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *User) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetLatestCheckin() int64 {
	if x != nil {
		return x.LatestCheckin
	}
	return 0
}

type AddBeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeerId        int64                  `protobuf:"varint,1,opt,name=beer_id,json=beerId,proto3" json:"beer_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SizeFlOz      int32                  `protobuf:"varint,3,opt,name=size_fl_oz,json=sizeFlOz,proto3" json:"size_fl_oz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBeerRequest) Reset() {
	*x = AddBeerRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBeerRequest) ProtoMessage() {}

func (x *AddBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBeerRequest.ProtoReflect.Descriptor instead.
func (*AddBeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddBeerRequest) GetBeerId() int64 {
	if x != nil {
		return x.BeerId
	}
	return 0
}

func (x *AddBeerRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddBeerRequest) GetSizeFlOz() int32 {
	if x != nil {
		return x.SizeFlOz
	}
	return 0
}

type AddBeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBeerResponse) Reset() {
	*x = AddBeerResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBeerResponse) ProtoMessage() {}

func (x *AddBeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBeerResponse.ProtoReflect.Descriptor instead.
func (*AddBeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type GetLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginRequest) Reset() {
	*x = GetLoginRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginRequest) ProtoMessage() {}

func (x *GetLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginRequest.ProtoReflect.Descriptor instead.
func (*GetLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type GetLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginResponse) Reset() {
	*x = GetLoginResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginResponse) ProtoMessage() {}

func (x *GetLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginResponse.ProtoReflect.Descriptor instead.
func (*GetLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetLoginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetLoginResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthTokenRequest) Reset() {
	*x = GetAuthTokenRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthTokenRequest) ProtoMessage() {}

func (x *GetAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthTokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthTokenResponse) Reset() {
	*x = GetAuthTokenResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthTokenResponse) ProtoMessage() {}

func (x *GetAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthTokenResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type HealthyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyRequest) Reset() {
	*x = HealthyRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyRequest) ProtoMessage() {}

func (x *HealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyRequest.ProtoReflect.Descriptor instead.
func (*HealthyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

type HealthyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyResponse) Reset() {
	*x = HealthyResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyResponse) ProtoMessage() {}

func (x *HealthyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyResponse.ProtoReflect.Descriptor instead.
func (*HealthyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

type GetCellarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellarRequest) Reset() {
	*x = GetCellarRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellarRequest) ProtoMessage() {}

func (x *GetCellarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellarRequest.ProtoReflect.Descriptor instead.
func (*GetCellarRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

type GetCellarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beers         []*Beer                `protobuf:"bytes,1,rep,name=beers,proto3" json:"beers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellarResponse) Reset() {
	*x = GetCellarResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellarResponse) ProtoMessage() {}

func (x *GetCellarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellarResponse.ProtoReflect.Descriptor instead.
func (*GetCellarResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetCellarResponse) GetBeers() []*Beer {
	if x != nil {
		return x.Beers
	}
	return nil
}

type GetBeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*BeerRequirement     `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	NoRepeat      bool                   `protobuf:"varint,2,opt,name=no_repeat,json=noRepeat,proto3" json:"no_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerRequest) Reset() {
	*x = GetBeerRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerRequest) ProtoMessage() {}

func (x *GetBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerRequest.ProtoReflect.Descriptor instead.
func (*GetBeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetBeerRequest) GetRequirements() []*BeerRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *GetBeerRequest) GetNoRepeat() bool {
	if x != nil {
		return x.NoRepeat
	}
	return false
}

type GetBeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beers         []*Beer                `protobuf:"bytes,1,rep,name=beers,proto3" json:"beers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerResponse) Reset() {
	*x = GetBeerResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerResponse) ProtoMessage() {}

func (x *GetBeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerResponse.ProtoReflect.Descriptor instead.
func (*GetBeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetBeerResponse) GetBeers() []*Beer {
	if x != nil {
		return x.Beers
	}
	return nil
}

type BeerRequirement struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	MaxUnits      int32                        `protobuf:"varint,1,opt,name=max_units,json=maxUnits,proto3" json:"max_units,omitempty"`
	Strategy      BeerRequirement_PickStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=beerkellar.BeerRequirement_PickStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeerRequirement) Reset() {
	*x = BeerRequirement{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeerRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeerRequirement) ProtoMessage() {}

func (x *BeerRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeerRequirement.ProtoReflect.Descriptor instead.
func (*BeerRequirement) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *BeerRequirement) GetMaxUnits() int32 {
	if x != nil {
		return x.MaxUnits
	}
	return 0
}

func (x *BeerRequirement) GetStrategy() BeerRequirement_PickStrategy {
	if x != nil {
		return x.Strategy
	}
	return BeerRequirement_STRATEGY_RANDOM
}

type SetRedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRedirectRequest) Reset() {
	*x = SetRedirectRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRedirectRequest) ProtoMessage() {}

func (x *SetRedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRedirectRequest.ProtoReflect.Descriptor instead.
func (*SetRedirectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *SetRedirectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetRedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRedirectResponse) Reset() {
	*x = SetRedirectResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRedirectResponse) ProtoMessage() {}

func (x *SetRedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRedirectResponse.ProtoReflect.Descriptor instead.
func (*SetRedirectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\n" +
	"beerkellar\x1a\n" +
	"beer.proto\"\x80\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12%\n" +
	"\x0elatest_checkin\x18\x04 \x01(\x03R\rlatestCheckin\"c\n" +
	"\x0eAddBeerRequest\x12\x17\n" +
	"\abeer_id\x18\x01 \x01(\x03R\x06beerId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1c\n" +
	"\n" +
	"size_fl_oz\x18\x03 \x01(\x05R\bsizeFlOz\"\x11\n" +
	"\x0fAddBeerResponse\"\x11\n" +
	"\x0fGetLoginRequest\"8\n" +
	"\x10GetLoginResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\")\n" +
	"\x13GetAuthTokenRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"*\n" +
	"\x14GetAuthTokenResponse\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x10\n" +
	"\x0eHealthyRequest\"\x11\n" +
	"\x0fHealthyResponse\"\x12\n" +
	"\x10GetCellarRequest\";\n" +
	"\x11GetCellarResponse\x12&\n" +
	"\x05beers\x18\x01 \x03(\v2\x10.beerkellar.BeerR\x05beers\"n\n" +
	"\x0eGetBeerRequest\x12?\n" +
	"\frequirements\x18\x01 \x03(\v2\x1b.beerkellar.BeerRequirementR\frequirements\x12\x1b\n" +
	"\tno_repeat\x18\x02 \x01(\bR\bnoRepeat\"9\n" +
	"\x0fGetBeerResponse\x12&\n" +
	"\x05beers\x18\x01 \x03(\v2\x10.beerkellar.BeerR\x05beers\"\xae\x01\n" +
	"\x0fBeerRequirement\x12\x1b\n" +
	"\tmax_units\x18\x01 \x01(\x05R\bmaxUnits\x12D\n" +
	"\bstrategy\x18\x02 \x01(\x0e2(.beerkellar.BeerRequirement.PickStrategyR\bstrategy\"8\n" +
	"\fPickStrategy\x12\x13\n" +
	"\x0fSTRATEGY_RANDOM\x10\x00\x12\x13\n" +
	"\x0fSTRATEGY_OLDEST\x10\x01\"&\n" +
	"\x12SetRedirectRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x15\n" +
	"\x13SetRedirectResponse2\xc8\x03\n" +
	"\n" +
	"BeerKeller\x12D\n" +
	"\aAddBeer\x12\x1a.beerkellar.AddBeerRequest\x1a\x1b.beerkellar.AddBeerResponse\"\x00\x12G\n" +
	"\bGetLogin\x12\x1b.beerkellar.GetLoginRequest\x1a\x1c.beerkellar.GetLoginResponse\"\x00\x12S\n" +
	"\fGetAuthToken\x12\x1f.beerkellar.GetAuthTokenRequest\x1a .beerkellar.GetAuthTokenResponse\"\x00\x12J\n" +
	"\tGetCellar\x12\x1c.beerkellar.GetCellarRequest\x1a\x1d.beerkellar.GetCellarResponse\"\x00\x12D\n" +
	"\aGetBeer\x12\x1a.beerkellar.GetBeerRequest\x1a\x1b.beerkellar.GetBeerResponse\"\x00\x12D\n" +
	"\aHealthy\x12\x1a.beerkellar.HealthyRequest\x1a\x1b.beerkellar.HealthyResponse\"\x002c\n" +
	"\x0fBeerKellerAdmin\x12P\n" +
	"\vSetRedirect\x12\x1e.beerkellar.SetRedirectRequest\x1a\x1f.beerkellar.SetRedirectResponse\"\x00B*Z(github.com/brotherlogic/beerkellar/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_goTypes = []any{
	(BeerRequirement_PickStrategy)(0), // 0: beerkellar.BeerRequirement.PickStrategy
	(*User)(nil),                      // 1: beerkellar.User
	(*AddBeerRequest)(nil),            // 2: beerkellar.AddBeerRequest
	(*AddBeerResponse)(nil),           // 3: beerkellar.AddBeerResponse
	(*GetLoginRequest)(nil),           // 4: beerkellar.GetLoginRequest
	(*GetLoginResponse)(nil),          // 5: beerkellar.GetLoginResponse
	(*GetAuthTokenRequest)(nil),       // 6: beerkellar.GetAuthTokenRequest
	(*GetAuthTokenResponse)(nil),      // 7: beerkellar.GetAuthTokenResponse
	(*HealthyRequest)(nil),            // 8: beerkellar.HealthyRequest
	(*HealthyResponse)(nil),           // 9: beerkellar.HealthyResponse
	(*GetCellarRequest)(nil),          // 10: beerkellar.GetCellarRequest
	(*GetCellarResponse)(nil),         // 11: beerkellar.GetCellarResponse
	(*GetBeerRequest)(nil),            // 12: beerkellar.GetBeerRequest
	(*GetBeerResponse)(nil),           // 13: beerkellar.GetBeerResponse
	(*BeerRequirement)(nil),           // 14: beerkellar.BeerRequirement
	(*SetRedirectRequest)(nil),        // 15: beerkellar.SetRedirectRequest
	(*SetRedirectResponse)(nil),       // 16: beerkellar.SetRedirectResponse
	(*Beer)(nil),                      // 17: beerkellar.Beer
}
var file_api_proto_depIdxs = []int32{
	17, // 0: beerkellar.GetCellarResponse.beers:type_name -> beerkellar.Beer
	14, // 1: beerkellar.GetBeerRequest.requirements:type_name -> beerkellar.BeerRequirement
	17, // 2: beerkellar.GetBeerResponse.beers:type_name -> beerkellar.Beer
	0,  // 3: beerkellar.BeerRequirement.strategy:type_name -> beerkellar.BeerRequirement.PickStrategy
	2,  // 4: beerkellar.BeerKeller.AddBeer:input_type -> beerkellar.AddBeerRequest
	4,  // 5: beerkellar.BeerKeller.GetLogin:input_type -> beerkellar.GetLoginRequest
	6,  // 6: beerkellar.BeerKeller.GetAuthToken:input_type -> beerkellar.GetAuthTokenRequest
	10, // 7: beerkellar.BeerKeller.GetCellar:input_type -> beerkellar.GetCellarRequest
	12, // 8: beerkellar.BeerKeller.GetBeer:input_type -> beerkellar.GetBeerRequest
	8,  // 9: beerkellar.BeerKeller.Healthy:input_type -> beerkellar.HealthyRequest
	15, // 10: beerkellar.BeerKellerAdmin.SetRedirect:input_type -> beerkellar.SetRedirectRequest
	3,  // 11: beerkellar.BeerKeller.AddBeer:output_type -> beerkellar.AddBeerResponse
	5,  // 12: beerkellar.BeerKeller.GetLogin:output_type -> beerkellar.GetLoginResponse
	7,  // 13: beerkellar.BeerKeller.GetAuthToken:output_type -> beerkellar.GetAuthTokenResponse
	11, // 14: beerkellar.BeerKeller.GetCellar:output_type -> beerkellar.GetCellarResponse
	13, // 15: beerkellar.BeerKeller.GetBeer:output_type -> beerkellar.GetBeerResponse
	9,  // 16: beerkellar.BeerKeller.Healthy:output_type -> beerkellar.HealthyResponse
	16, // 17: beerkellar.BeerKellerAdmin.SetRedirect:output_type -> beerkellar.SetRedirectResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_beer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
