// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BeerKellerClient is the client API for BeerKeller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeerKellerClient interface {
	AddBeer(ctx context.Context, in *AddBeerRequest, opts ...grpc.CallOption) (*AddBeerResponse, error)
	GetLogin(ctx context.Context, in *GetLoginRequest, opts ...grpc.CallOption) (*GetLoginResponse, error)
	GetAuthToken(ctx context.Context, in *GetAuthTokenRequest, opts ...grpc.CallOption) (*GetAuthTokenResponse, error)
	GetCellar(ctx context.Context, in *GetCellarRequest, opts ...grpc.CallOption) (*GetCellarResponse, error)
	GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*GetBeerResponse, error)
	Healthy(ctx context.Context, in *HealthyRequest, opts ...grpc.CallOption) (*HealthyResponse, error)
}

type beerKellerClient struct {
	cc grpc.ClientConnInterface
}

func NewBeerKellerClient(cc grpc.ClientConnInterface) BeerKellerClient {
	return &beerKellerClient{cc}
}

func (c *beerKellerClient) AddBeer(ctx context.Context, in *AddBeerRequest, opts ...grpc.CallOption) (*AddBeerResponse, error) {
	out := new(AddBeerResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/AddBeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerKellerClient) GetLogin(ctx context.Context, in *GetLoginRequest, opts ...grpc.CallOption) (*GetLoginResponse, error) {
	out := new(GetLoginResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/GetLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerKellerClient) GetAuthToken(ctx context.Context, in *GetAuthTokenRequest, opts ...grpc.CallOption) (*GetAuthTokenResponse, error) {
	out := new(GetAuthTokenResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/GetAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerKellerClient) GetCellar(ctx context.Context, in *GetCellarRequest, opts ...grpc.CallOption) (*GetCellarResponse, error) {
	out := new(GetCellarResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/GetCellar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerKellerClient) GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*GetBeerResponse, error) {
	out := new(GetBeerResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/GetBeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerKellerClient) Healthy(ctx context.Context, in *HealthyRequest, opts ...grpc.CallOption) (*HealthyResponse, error) {
	out := new(HealthyResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKeller/Healthy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeerKellerServer is the server API for BeerKeller service.
// All implementations should embed UnimplementedBeerKellerServer
// for forward compatibility
type BeerKellerServer interface {
	AddBeer(context.Context, *AddBeerRequest) (*AddBeerResponse, error)
	GetLogin(context.Context, *GetLoginRequest) (*GetLoginResponse, error)
	GetAuthToken(context.Context, *GetAuthTokenRequest) (*GetAuthTokenResponse, error)
	GetCellar(context.Context, *GetCellarRequest) (*GetCellarResponse, error)
	GetBeer(context.Context, *GetBeerRequest) (*GetBeerResponse, error)
	Healthy(context.Context, *HealthyRequest) (*HealthyResponse, error)
}

// UnimplementedBeerKellerServer should be embedded to have forward compatible implementations.
type UnimplementedBeerKellerServer struct {
}

func (UnimplementedBeerKellerServer) AddBeer(context.Context, *AddBeerRequest) (*AddBeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBeer not implemented")
}
func (UnimplementedBeerKellerServer) GetLogin(context.Context, *GetLoginRequest) (*GetLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogin not implemented")
}
func (UnimplementedBeerKellerServer) GetAuthToken(context.Context, *GetAuthTokenRequest) (*GetAuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthToken not implemented")
}
func (UnimplementedBeerKellerServer) GetCellar(context.Context, *GetCellarRequest) (*GetCellarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCellar not implemented")
}
func (UnimplementedBeerKellerServer) GetBeer(context.Context, *GetBeerRequest) (*GetBeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeer not implemented")
}
func (UnimplementedBeerKellerServer) Healthy(context.Context, *HealthyRequest) (*HealthyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthy not implemented")
}

// UnsafeBeerKellerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeerKellerServer will
// result in compilation errors.
type UnsafeBeerKellerServer interface {
	mustEmbedUnimplementedBeerKellerServer()
}

func RegisterBeerKellerServer(s grpc.ServiceRegistrar, srv BeerKellerServer) {
	s.RegisterService(&BeerKeller_ServiceDesc, srv)
}

func _BeerKeller_AddBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).AddBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/AddBeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).AddBeer(ctx, req.(*AddBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerKeller_GetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).GetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/GetLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).GetLogin(ctx, req.(*GetLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerKeller_GetAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).GetAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/GetAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).GetAuthToken(ctx, req.(*GetAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerKeller_GetCellar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).GetCellar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/GetCellar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).GetCellar(ctx, req.(*GetCellarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerKeller_GetBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).GetBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/GetBeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).GetBeer(ctx, req.(*GetBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerKeller_Healthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerServer).Healthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKeller/Healthy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerServer).Healthy(ctx, req.(*HealthyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeerKeller_ServiceDesc is the grpc.ServiceDesc for BeerKeller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeerKeller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beerkellar.BeerKeller",
	HandlerType: (*BeerKellerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBeer",
			Handler:    _BeerKeller_AddBeer_Handler,
		},
		{
			MethodName: "GetLogin",
			Handler:    _BeerKeller_GetLogin_Handler,
		},
		{
			MethodName: "GetAuthToken",
			Handler:    _BeerKeller_GetAuthToken_Handler,
		},
		{
			MethodName: "GetCellar",
			Handler:    _BeerKeller_GetCellar_Handler,
		},
		{
			MethodName: "GetBeer",
			Handler:    _BeerKeller_GetBeer_Handler,
		},
		{
			MethodName: "Healthy",
			Handler:    _BeerKeller_Healthy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// BeerKellerAdminClient is the client API for BeerKellerAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeerKellerAdminClient interface {
	SetRedirect(ctx context.Context, in *SetRedirectRequest, opts ...grpc.CallOption) (*SetRedirectResponse, error)
}

type beerKellerAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewBeerKellerAdminClient(cc grpc.ClientConnInterface) BeerKellerAdminClient {
	return &beerKellerAdminClient{cc}
}

func (c *beerKellerAdminClient) SetRedirect(ctx context.Context, in *SetRedirectRequest, opts ...grpc.CallOption) (*SetRedirectResponse, error) {
	out := new(SetRedirectResponse)
	err := c.cc.Invoke(ctx, "/beerkellar.BeerKellerAdmin/SetRedirect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeerKellerAdminServer is the server API for BeerKellerAdmin service.
// All implementations should embed UnimplementedBeerKellerAdminServer
// for forward compatibility
type BeerKellerAdminServer interface {
	SetRedirect(context.Context, *SetRedirectRequest) (*SetRedirectResponse, error)
}

// UnimplementedBeerKellerAdminServer should be embedded to have forward compatible implementations.
type UnimplementedBeerKellerAdminServer struct {
}

func (UnimplementedBeerKellerAdminServer) SetRedirect(context.Context, *SetRedirectRequest) (*SetRedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRedirect not implemented")
}

// UnsafeBeerKellerAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeerKellerAdminServer will
// result in compilation errors.
type UnsafeBeerKellerAdminServer interface {
	mustEmbedUnimplementedBeerKellerAdminServer()
}

func RegisterBeerKellerAdminServer(s grpc.ServiceRegistrar, srv BeerKellerAdminServer) {
	s.RegisterService(&BeerKellerAdmin_ServiceDesc, srv)
}

func _BeerKellerAdmin_SetRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerKellerAdminServer).SetRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beerkellar.BeerKellerAdmin/SetRedirect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerKellerAdminServer).SetRedirect(ctx, req.(*SetRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeerKellerAdmin_ServiceDesc is the grpc.ServiceDesc for BeerKellerAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeerKellerAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beerkellar.BeerKellerAdmin",
	HandlerType: (*BeerKellerAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRedirect",
			Handler:    _BeerKellerAdmin_SetRedirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
