// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: beerkellar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cellar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CellarEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cellar) Reset() {
	*x = Cellar{}
	mi := &file_beerkellar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cellar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cellar) ProtoMessage() {}

func (x *Cellar) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cellar.ProtoReflect.Descriptor instead.
func (*Cellar) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{0}
}

func (x *Cellar) GetEntries() []*CellarEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CellarEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeerId        int64                  `protobuf:"varint,1,opt,name=beer_id,json=beerId,proto3" json:"beer_id,omitempty"`
	DateAdded     int64                  `protobuf:"varint,2,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	SizeFlOz      int32                  `protobuf:"varint,3,opt,name=size_fl_oz,json=sizeFlOz,proto3" json:"size_fl_oz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellarEntry) Reset() {
	*x = CellarEntry{}
	mi := &file_beerkellar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellarEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellarEntry) ProtoMessage() {}

func (x *CellarEntry) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellarEntry.ProtoReflect.Descriptor instead.
func (*CellarEntry) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{1}
}

func (x *CellarEntry) GetBeerId() int64 {
	if x != nil {
		return x.BeerId
	}
	return 0
}

func (x *CellarEntry) GetDateAdded() int64 {
	if x != nil {
		return x.DateAdded
	}
	return 0
}

func (x *CellarEntry) GetSizeFlOz() int32 {
	if x != nil {
		return x.SizeFlOz
	}
	return 0
}

type DrinkArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrinkArchive) Reset() {
	*x = DrinkArchive{}
	mi := &file_beerkellar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrinkArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrinkArchive) ProtoMessage() {}

func (x *DrinkArchive) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrinkArchive.ProtoReflect.Descriptor instead.
func (*DrinkArchive) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{2}
}

func (x *DrinkArchive) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type Drink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeerId        int64                  `protobuf:"varint,1,opt,name=beer_id,json=beerId,proto3" json:"beer_id,omitempty"`
	Date          int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_beerkellar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{3}
}

func (x *Drink) GetBeerId() int64 {
	if x != nil {
		return x.BeerId
	}
	return 0
}

func (x *Drink) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Drink) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_beerkellar_proto protoreflect.FileDescriptor

const file_beerkellar_proto_rawDesc = "" +
	"\n" +
	"\x10beerkellar.proto\x12\n" +
	"beerkellar\";\n" +
	"\x06Cellar\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.beerkellar.CellarEntryR\aentries\"c\n" +
	"\vCellarEntry\x12\x17\n" +
	"\abeer_id\x18\x01 \x01(\x03R\x06beerId\x12\x1d\n" +
	"\n" +
	"date_added\x18\x02 \x01(\x03R\tdateAdded\x12\x1c\n" +
	"\n" +
	"size_fl_oz\x18\x03 \x01(\x05R\bsizeFlOz\"9\n" +
	"\fDrinkArchive\x12)\n" +
	"\x06drinks\x18\x01 \x03(\v2\x11.beerkellar.DrinkR\x06drinks\"J\n" +
	"\x05Drink\x12\x17\n" +
	"\abeer_id\x18\x01 \x01(\x03R\x06beerId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05scoreB*Z(github.com/brotherlogic/beerkellar/protob\x06proto3"

var (
	file_beerkellar_proto_rawDescOnce sync.Once
	file_beerkellar_proto_rawDescData []byte
)

func file_beerkellar_proto_rawDescGZIP() []byte {
	file_beerkellar_proto_rawDescOnce.Do(func() {
		file_beerkellar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerkellar_proto_rawDesc), len(file_beerkellar_proto_rawDesc)))
	})
	return file_beerkellar_proto_rawDescData
}

var file_beerkellar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_beerkellar_proto_goTypes = []any{
	(*Cellar)(nil),       // 0: beerkellar.Cellar
	(*CellarEntry)(nil),  // 1: beerkellar.CellarEntry
	(*DrinkArchive)(nil), // 2: beerkellar.DrinkArchive
	(*Drink)(nil),        // 3: beerkellar.Drink
}
var file_beerkellar_proto_depIdxs = []int32{
	1, // 0: beerkellar.Cellar.entries:type_name -> beerkellar.CellarEntry
	3, // 1: beerkellar.DrinkArchive.drinks:type_name -> beerkellar.Drink
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_beerkellar_proto_init() }
func file_beerkellar_proto_init() {
	if File_beerkellar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerkellar_proto_rawDesc), len(file_beerkellar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beerkellar_proto_goTypes,
		DependencyIndexes: file_beerkellar_proto_depIdxs,
		MessageInfos:      file_beerkellar_proto_msgTypes,
	}.Build()
	File_beerkellar_proto = out.File
	file_beerkellar_proto_goTypes = nil
	file_beerkellar_proto_depIdxs = nil
}
