// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: beer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Beer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abv           float32                `protobuf:"fixed32,3,opt,name=abv,proto3" json:"abv,omitempty"`
	Brewery       string                 `protobuf:"bytes,4,opt,name=brewery,proto3" json:"brewery,omitempty"`
	GlobalScore   float32                `protobuf:"fixed32,5,opt,name=global_score,json=globalScore,proto3" json:"global_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beer) Reset() {
	*x = Beer{}
	mi := &file_beer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beer) ProtoMessage() {}

func (x *Beer) ProtoReflect() protoreflect.Message {
	mi := &file_beer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beer.ProtoReflect.Descriptor instead.
func (*Beer) Descriptor() ([]byte, []int) {
	return file_beer_proto_rawDescGZIP(), []int{0}
}

func (x *Beer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beer) GetAbv() float32 {
	if x != nil {
		return x.Abv
	}
	return 0
}

func (x *Beer) GetBrewery() string {
	if x != nil {
		return x.Brewery
	}
	return ""
}

func (x *Beer) GetGlobalScore() float32 {
	if x != nil {
		return x.GlobalScore
	}
	return 0
}

var File_beer_proto protoreflect.FileDescriptor

const file_beer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"beer.proto\x12\n" +
	"beerkellar\"y\n" +
	"\x04Beer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03abv\x18\x03 \x01(\x02R\x03abv\x12\x18\n" +
	"\abrewery\x18\x04 \x01(\tR\abrewery\x12!\n" +
	"\fglobal_score\x18\x05 \x01(\x02R\vglobalScoreB*Z(github.com/brotherlogic/beerkellar/protob\x06proto3"

var (
	file_beer_proto_rawDescOnce sync.Once
	file_beer_proto_rawDescData []byte
)

func file_beer_proto_rawDescGZIP() []byte {
	file_beer_proto_rawDescOnce.Do(func() {
		file_beer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beer_proto_rawDesc), len(file_beer_proto_rawDesc)))
	})
	return file_beer_proto_rawDescData
}

var file_beer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beer_proto_goTypes = []any{
	(*Beer)(nil), // 0: beerkellar.Beer
}
var file_beer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beer_proto_init() }
func file_beer_proto_init() {
	if File_beer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beer_proto_rawDesc), len(file_beer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beer_proto_goTypes,
		DependencyIndexes: file_beer_proto_depIdxs,
		MessageInfos:      file_beer_proto_msgTypes,
	}.Build()
	File_beer_proto = out.File
	file_beer_proto_goTypes = nil
	file_beer_proto_depIdxs = nil
}
