// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: beerkellar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBeerRequest_GetBeerType int32

const (
	GetBeerRequest_GET_BEER_TYPE_UNSPECIFIED GetBeerRequest_GetBeerType = 0
	GetBeerRequest_GET_BEER_TYPE_SESSION     GetBeerRequest_GetBeerType = 1
	GetBeerRequest_GET_BEER_TYPE_BEST        GetBeerRequest_GetBeerType = 2
)

// Enum value maps for GetBeerRequest_GetBeerType.
var (
	GetBeerRequest_GetBeerType_name = map[int32]string{
		0: "GET_BEER_TYPE_UNSPECIFIED",
		1: "GET_BEER_TYPE_SESSION",
		2: "GET_BEER_TYPE_BEST",
	}
	GetBeerRequest_GetBeerType_value = map[string]int32{
		"GET_BEER_TYPE_UNSPECIFIED": 0,
		"GET_BEER_TYPE_SESSION":     1,
		"GET_BEER_TYPE_BEST":        2,
	}
)

func (x GetBeerRequest_GetBeerType) Enum() *GetBeerRequest_GetBeerType {
	p := new(GetBeerRequest_GetBeerType)
	*p = x
	return p
}

func (x GetBeerRequest_GetBeerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBeerRequest_GetBeerType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerkellar_proto_enumTypes[0].Descriptor()
}

func (GetBeerRequest_GetBeerType) Type() protoreflect.EnumType {
	return &file_beerkellar_proto_enumTypes[0]
}

func (x GetBeerRequest_GetBeerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetBeerRequest_GetBeerType.Descriptor instead.
func (GetBeerRequest_GetBeerType) EnumDescriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{2, 0}
}

type AddBeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeerId int32 `protobuf:"varint,1,opt,name=beer_id,json=beerId,proto3" json:"beer_id,omitempty"`
}

func (x *AddBeerRequest) Reset() {
	*x = AddBeerRequest{}
	mi := &file_beerkellar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBeerRequest) ProtoMessage() {}

func (x *AddBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBeerRequest.ProtoReflect.Descriptor instead.
func (*AddBeerRequest) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{0}
}

func (x *AddBeerRequest) GetBeerId() int32 {
	if x != nil {
		return x.BeerId
	}
	return 0
}

type AddBeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBeerResponse) Reset() {
	*x = AddBeerResponse{}
	mi := &file_beerkellar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBeerResponse) ProtoMessage() {}

func (x *AddBeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBeerResponse.ProtoReflect.Descriptor instead.
func (*AddBeerResponse) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{1}
}

type GetBeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GetBeerRequest_GetBeerType `protobuf:"varint,1,opt,name=type,proto3,enum=beerkellar.GetBeerRequest_GetBeerType" json:"type,omitempty"`
}

func (x *GetBeerRequest) Reset() {
	*x = GetBeerRequest{}
	mi := &file_beerkellar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerRequest) ProtoMessage() {}

func (x *GetBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerRequest.ProtoReflect.Descriptor instead.
func (*GetBeerRequest) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{2}
}

func (x *GetBeerRequest) GetType() GetBeerRequest_GetBeerType {
	if x != nil {
		return x.Type
	}
	return GetBeerRequest_GET_BEER_TYPE_UNSPECIFIED
}

type GetBeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeerId      int32  `protobuf:"varint,1,opt,name=beer_id,json=beerId,proto3" json:"beer_id,omitempty"`
	BreweryName string `protobuf:"bytes,2,opt,name=brewery_name,json=breweryName,proto3" json:"brewery_name,omitempty"`
	BeerName    string `protobuf:"bytes,3,opt,name=beer_name,json=beerName,proto3" json:"beer_name,omitempty"`
}

func (x *GetBeerResponse) Reset() {
	*x = GetBeerResponse{}
	mi := &file_beerkellar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerResponse) ProtoMessage() {}

func (x *GetBeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beerkellar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerResponse.ProtoReflect.Descriptor instead.
func (*GetBeerResponse) Descriptor() ([]byte, []int) {
	return file_beerkellar_proto_rawDescGZIP(), []int{3}
}

func (x *GetBeerResponse) GetBeerId() int32 {
	if x != nil {
		return x.BeerId
	}
	return 0
}

func (x *GetBeerResponse) GetBreweryName() string {
	if x != nil {
		return x.BreweryName
	}
	return ""
}

func (x *GetBeerResponse) GetBeerName() string {
	if x != nil {
		return x.BeerName
	}
	return ""
}

var File_beerkellar_proto protoreflect.FileDescriptor

var file_beerkellar_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x22, 0x29,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x62, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x62, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xad, 0x01, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e,
	0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x47, 0x45,
	0x54, 0x5f, 0x42, 0x45, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x47, 0x45, 0x54,
	0x5f, 0x42, 0x45, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x45, 0x54, 0x5f, 0x42, 0x45, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x53, 0x54, 0x10, 0x02, 0x22, 0x6a, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x62, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x62, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x72, 0x65, 0x77,
	0x65, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x62, 0x72, 0x65, 0x77, 0x65, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x65, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x65, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x98, 0x01, 0x0a, 0x0a, 0x42, 0x65, 0x65,
	0x72, 0x4b, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x65,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e,
	0x41, 0x64, 0x64, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x42,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x62, 0x65, 0x65, 0x72, 0x6b,
	0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x62,
	0x65, 0x65, 0x72, 0x6b, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beerkellar_proto_rawDescOnce sync.Once
	file_beerkellar_proto_rawDescData = file_beerkellar_proto_rawDesc
)

func file_beerkellar_proto_rawDescGZIP() []byte {
	file_beerkellar_proto_rawDescOnce.Do(func() {
		file_beerkellar_proto_rawDescData = protoimpl.X.CompressGZIP(file_beerkellar_proto_rawDescData)
	})
	return file_beerkellar_proto_rawDescData
}

var file_beerkellar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_beerkellar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_beerkellar_proto_goTypes = []any{
	(GetBeerRequest_GetBeerType)(0), // 0: beerkellar.GetBeerRequest.GetBeerType
	(*AddBeerRequest)(nil),          // 1: beerkellar.AddBeerRequest
	(*AddBeerResponse)(nil),         // 2: beerkellar.AddBeerResponse
	(*GetBeerRequest)(nil),          // 3: beerkellar.GetBeerRequest
	(*GetBeerResponse)(nil),         // 4: beerkellar.GetBeerResponse
}
var file_beerkellar_proto_depIdxs = []int32{
	0, // 0: beerkellar.GetBeerRequest.type:type_name -> beerkellar.GetBeerRequest.GetBeerType
	1, // 1: beerkellar.BeerKeller.AddBeer:input_type -> beerkellar.AddBeerRequest
	3, // 2: beerkellar.BeerKeller.GetBeer:input_type -> beerkellar.GetBeerRequest
	2, // 3: beerkellar.BeerKeller.AddBeer:output_type -> beerkellar.AddBeerResponse
	4, // 4: beerkellar.BeerKeller.GetBeer:output_type -> beerkellar.GetBeerResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beerkellar_proto_init() }
func file_beerkellar_proto_init() {
	if File_beerkellar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beerkellar_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beerkellar_proto_goTypes,
		DependencyIndexes: file_beerkellar_proto_depIdxs,
		EnumInfos:         file_beerkellar_proto_enumTypes,
		MessageInfos:      file_beerkellar_proto_msgTypes,
	}.Build()
	File_beerkellar_proto = out.File
	file_beerkellar_proto_rawDesc = nil
	file_beerkellar_proto_goTypes = nil
	file_beerkellar_proto_depIdxs = nil
}
